import { ensureTestFinancialAccount } from "./helpers/finance";
import { expect, test } from "@playwright/test";
import { signInWithRetry } from "./helpers/auth";

test("reverses a reconciled receipt and reopens the same client title", async ({ page }) => {
  test.setTimeout(150_000);
  await signInWithRetry(page, "todos.perfis@formula.local", process.env.DEMO_USER_PASSWORD!);
  await ensureTestFinancialAccount(page);
  const marker = `HML-estorno-${Date.now()}`;
  const now = new Date();
  const competence = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  const label = `${competence.slice(5)}/${competence.slice(0, 4)}`;
  await page.goto(`/app/financeiro/relatorios?month=${competence}`);
  const cashRow = page.getByRole("row").filter({ has: page.getByRole("rowheader", { name: "Conta Gráfica QA", exact: true }) });
  const previousReversedIncome = Number((await cashRow.getByRole("cell").nth(3).innerText()).replace(/\D/g, ""));
  await page.goto("/app/clientes/novo");
  await page.locator('[name="name"]').fill(marker);
  await page.locator(".fg-input-wrap").filter({ has: page.locator('[name="monthlyFee"]') }).locator('input[type="text"]').fill("100,00");
  await page.locator('[name="billingDay"]').fill("15");
  await page.getByRole("button", { name: "Criar cliente", exact: true }).click();
  await expect(page.getByRole("heading", { name: marker, exact: true })).toBeVisible();
  const clientUrl = page.url();
  await page.locator("button").filter({ hasText: /^Gerar entrada$/ }).click();
  const generate = page.locator("form").filter({ has: page.locator('[name="competence"]') });
  await generate.locator('[name="competence"]').fill(competence);
  await Promise.all([page.waitForResponse(response => response.request().method() === "POST" && response.url().includes("/app/clientes/")), generate.locator('button[type="submit"]').click()]);
  await page.goto("/app/financeiro/movimentacoes");
  await page.getByRole("combobox", { name: /^Conta financeira/ }).selectOption({ label: "Conta Gráfica QA" });
  await page.getByRole("textbox", { name: /^Valor/ }).fill("100,00");
  await page.getByLabel("Cliente", { exact: true }).selectOption({ label: marker });
  await page.getByLabel("Referência", { exact: true }).fill(marker);
  await page.getByRole("button", { name: "Registrar movimentação", exact: true }).click();
  await page.getByRole("row").filter({ has: page.getByRole("cell", { name: marker, exact: true }) }).getByRole("link", { name: "Conciliar", exact: true }).click();
  await page.getByLabel("Buscar por descrição, código do trabalho ou contraparte", { exact: true }).fill(marker);
  await page.getByRole("button", { name: "Buscar títulos", exact: true }).click();
  await page.getByLabel(`Valor para Fee ${label} - ${marker}`, { exact: true }).fill("100,00");
  await page.getByRole("checkbox", { name: "Conferi os títulos e valores e confirmo a conciliação.", exact: true }).check();
  await page.getByRole("button", { name: "Confirmar conciliação", exact: true }).click();
  await expect(page.getByText("Saldo a conciliar: R$ 0,00", { exact: true })).toBeVisible();
  await page.getByLabel("Motivo do estorno").fill("Recebimento registrado por engano");
  await page.getByRole("button", { name: "Confirmar estorno", exact: true }).click();
  await expect(page.getByText(/Motivo: Recebimento registrado por engano/)).toBeVisible();
  await expect(page.getByRole("button", { name: "Confirmar estorno", exact: true })).toHaveCount(0);
  await expect(page.getByRole("listitem").filter({ hasText: marker })).toContainText("R$ 100,00");
  await page.reload();
  await expect(page.getByText(/Vínculos históricos da movimentação estornada/)).toBeVisible();
  await page.goto(`${clientUrl}?tab=pagamentos`);
  const payment = page.getByRole("row").filter({ has: page.getByRole("cell", { name: label, exact: true }) });
  await expect(payment.getByRole("cell").nth(2)).toHaveText("R$ 100,00");
  await expect(payment.getByRole("cell").nth(3)).toHaveText("R$ 0,00");
  await expect(payment).not.toContainText("Recebido");
  await page.goto(`/app/financeiro/relatorios?month=${competence}`);
  const reversedIncome = Number((await cashRow.getByRole("cell").nth(3).innerText()).replace(/\D/g, ""));
  expect(reversedIncome - previousReversedIncome).toBe(10000);
  await page.reload();
  await expect(cashRow.getByRole("cell").nth(3)).toHaveText(new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(reversedIncome / 100));
});
