import { expect, test } from "@playwright/test";

test("graphic flow from competing quotes and rejection to OS, production, reconciliation and closure", async ({ page }) => {
  test.setTimeout(120_000);
  const password = process.env.DEMO_USER_PASSWORD;
  expect(password, "Set DEMO_USER_PASSWORD for the local demo account").toBeTruthy();
  const signIn = () => page.request.post("/api/auth/sign-in/email", { data: { email: "todos.perfis@formula.local", password } });
  let login = await signIn();
  if (login.status() === 429) {
    // Honor the real auth limiter when running after the other demo login tests.
    const seconds = Number(login.headers()["retry-after"] ?? 10);
    await new Promise(resolve => setTimeout(resolve, (Math.min(Math.max(seconds, 1), 30) + 1) * 1000));
    login = await signIn();
  }
  expect(login.ok()).toBe(true);
  await page.goto("/app/financeiro/cadastros");
  const accounts = page.locator(".fg-card").filter({ has: page.getByText("Contas financeiras", { exact: true }) });
  if (!(await accounts.getByText("Conta Gráfica QA", { exact: true }).count())) {
    await accounts.getByText("Novo cadastro", { exact: true }).click();
    await accounts.locator("form").filter({ has: page.getByRole("button", { name: "Adicionar conta", exact: true }) }).locator('input[name="name"]').fill("Conta Gráfica QA");
    await accounts.getByRole("button", { name: "Adicionar conta", exact: true }).click();
    await expect(accounts.getByText("Conta Gráfica QA", { exact: true })).toBeVisible();
  }
  const categories = page.locator(".fg-card").filter({ has: page.getByText("Categorias financeiras", { exact: true }) });
  if (!(await categories.getByText("Custos Gráfica QA", { exact: true }).count())) {
    await categories.getByText("Novo cadastro", { exact: true }).click();
    await categories.locator('form').filter({ has: page.getByRole("button", { name: "Adicionar categoria", exact: true }) }).locator('input[name="name"]').fill("Custos Gráfica QA");
    await categories.locator('form').filter({ has: page.getByRole("button", { name: "Adicionar categoria", exact: true }) }).locator('select[name="nature"]').selectOption("expense");
    await categories.getByRole("button", { name: "Adicionar categoria", exact: true }).click();
    await expect(categories.getByText("Custos Gráfica QA", { exact: true })).toBeVisible();
  }
  const code = `OS-E2E-${Date.now()}`;
  await page.goto("/app/grafica/novo");
  await page.getByRole("textbox", { name: "Código interno", exact: true }).fill(code);
  await page.getByRole("textbox", { name: "Título", exact: true }).fill("QA - Registro de OS externa");
  await page.getByRole("combobox", { name: "Cliente", exact: true }).selectOption({ label: "Horizonte Eventos - Grafica" });
  await page.getByRole("combobox", { name: "Responsável", exact: true }).selectOption({ label: "Lideranca Demo" });
  await page.getByRole("textbox", { name: "Data da solicitação", exact: true }).fill("2026-09-21");
  await page.getByRole("textbox", { name: "Descrição", exact: true }).fill("Trabalho fictício para validar GRF-005.");
  await page.getByRole("button", { name: "Criar trabalho", exact: true }).click();
  await expect(page.getByRole("heading", { name: "QA - Registro de OS externa" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Registrar OS", exact: true })).toHaveCount(0);
  await page.getByRole("combobox", { name: "Fornecedor", exact: true }).selectOption({ label: "Fornecedor QA Grafica A" });
  await page.getByRole("textbox", { name: "Valor cotado", exact: true }).fill("1500,00");
  await page.getByRole("textbox", { name: "Descrição", exact: true }).fill("Primeira cotação acima do orçamento");
  await page.getByRole("button", { name: "Adicionar cotação", exact: true }).click();
  await page.getByLabel("Motivo da rejeição", { exact: true }).fill("Valor acima do orçamento; consultar alternativa");
  await page.getByRole("button", { name: "Rejeitar cotação", exact: true }).click();
  await expect(page.getByText("Valor acima do orçamento; consultar alternativa", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Registrar OS", exact: true })).toHaveCount(0);
  await page.getByRole("combobox", { name: "Fornecedor", exact: true }).selectOption({ label: "Fornecedor QA Grafica B" });
  await page.getByRole("textbox", { name: "Valor cotado", exact: true }).fill("1200,00");
  await page.getByRole("textbox", { name: "Descrição", exact: true }).fill("Cotação de teste para OS");
  await page.getByRole("button", { name: "Adicionar cotação", exact: true }).click();
  await page.getByRole("button", { name: "Aprovar cotação", exact: true }).click();
  await expect(page.getByRole("button", { name: "Registrar OS", exact: true })).toBeVisible();
  // Minimal PDF fixture for transport and version-preservation assertions.
  const pdf = Buffer.from("%PDF-1.4\n1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n2 0 obj\n<< /Type /Pages /Kids [] /Count 0 >>\nendobj\ntrailer\n<< /Root 1 0 R >>\n%%EOF\n");
  await page.getByLabel("Número da OS", { exact: true }).fill("QA-OS-COMPARTILHADA");
  await page.getByLabel("Data da OS", { exact: true }).fill("2026-09-21");
  await page.getByLabel("Valor apresentado ao cliente", { exact: true }).fill("1.800,00");
  await page.getByLabel("PDF da OS", { exact: true }).setInputFiles({ name: "os-qa-v1.pdf", mimeType: "application/pdf", buffer: pdf });
  await page.getByRole("button", { name: "Registrar OS", exact: true }).click();
  await expect(page.getByText("Aguardando cliente", { exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: "Baixar PDF da versão 1" })).toBeVisible();
  const originalUrl = await page.getByRole("link", { name: "Baixar PDF da versão 1" }).getAttribute("href");
  const first = await page.request.get(originalUrl!);
  expect(first.status()).toBe(200);
  expect(await first.body()).toEqual(pdf);
  expect(first.headers()["cache-control"]).toContain("no-store");
  await page.getByRole("combobox", { name: "Resposta do cliente", exact: true }).selectOption("revision_requested");
  await page.getByLabel("Contato do cliente", { exact: true }).fill("Cliente de teste");
  await page.getByRole("combobox", { name: "Canal da resposta", exact: true }).selectOption("email");
  await page.getByLabel("Data da resposta", { exact: true }).fill("2026-09-21");
  await page.getByLabel("Motivo ou alteração solicitada", { exact: true }).fill("Ajustar a arte e o valor");
  await page.getByLabel("Evidência da resposta (opcional)", { exact: true }).setInputFiles({ name: "resposta.pdf", mimeType: "application/pdf", buffer: pdf });
  await page.getByRole("button", { name: "Registrar resposta do cliente", exact: true }).click();
  await expect(page.getByText("Alteração solicitada · OS versão 1", { exact: true })).toBeVisible();
  const evidenceUrl = await page.getByRole("link", { name: "Baixar evidência da resposta", exact: true }).getAttribute("href");
  expect(await (await page.request.get(evidenceUrl!)).body()).toEqual(pdf);
  await page.getByLabel("Valor apresentado ao cliente", { exact: true }).fill("1950,00");
  await page.getByLabel("Motivo da nova versão", { exact: true }).fill("Alteração da arte e do valor");
  await page.getByLabel("PDF da OS", { exact: true }).setInputFiles({ name: "os-qa-v2.pdf", mimeType: "application/pdf", buffer: pdf });
  await page.getByRole("button", { name: "Registrar nova versão da OS", exact: true }).click();
  await expect(page.getByRole("link", { name: "Baixar PDF da versão 2" })).toBeVisible();
  await expect(page.getByRole("link", { name: "Baixar PDF da versão 1" })).toBeVisible();
  expect(await (await page.request.get(originalUrl!)).body()).toEqual(pdf);
  await page.getByRole("combobox", { name: "Resposta do cliente", exact: true }).selectOption("approved");
  await page.getByLabel("Contato do cliente", { exact: true }).fill("Cliente de teste");
  await page.getByRole("combobox", { name: "Canal da resposta", exact: true }).selectOption("whatsapp");
  await page.getByLabel("Data da resposta", { exact: true }).fill("2026-09-21");
  await page.getByRole("button", { name: "Registrar resposta do cliente", exact: true }).click();
  await expect(page.getByText("Aprovado · OS versão 2", { exact: true })).toBeVisible();
  await expect(page.getByText("Alteração solicitada · OS versão 1", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Registrar nova versão da OS", exact: true })).toHaveCount(0);
  await page.getByLabel("Data da contratação", { exact: true }).fill("2026-09-21");
  await page.getByLabel("Vencimento do fornecedor", { exact: true }).fill("2026-10-01");
  await page.getByLabel("Competência do custo", { exact: true }).fill("2026-09");
  await page.getByRole("combobox", { name: "Categoria do custo", exact: true }).selectOption({ label: "Custos Gráfica QA" });
  await page.getByRole("checkbox", { name: "Confirmo a contratação e a criação da conta a pagar.", exact: true }).check();
  await page.getByRole("button", { name: "Contratar fornecedor e criar conta a pagar", exact: true }).click();
  await expect(page.getByText("Conta a pagar criada. Pagamento acompanhado pelo Financeiro.", { exact: true })).toBeVisible();
  await page.getByLabel("Competência da venda", { exact: true }).fill("2026-09");
  await page.getByLabel("Descrição da parcela 1", { exact: true }).fill("Sinal");
  await page.getByLabel("Valor da parcela 1", { exact: true }).fill("500,00");
  await page.getByLabel("Vencimento da parcela 1", { exact: true }).fill("2026-09-21");
  await page.getByRole("button", { name: "Adicionar parcela", exact: true }).click();
  await page.getByLabel("Descrição da parcela 2", { exact: true }).fill("Saldo");
  await page.getByLabel("Valor da parcela 2", { exact: true }).fill("1000,00");
  await page.getByLabel("Vencimento da parcela 2", { exact: true }).fill("2026-10-01");
  await page.getByRole("checkbox", { name: "Confirmo as condições comerciais e a criação das contas a receber.", exact: true }).check();
  await page.getByRole("button", { name: "Registrar venda e criar contas a receber", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: "A soma das parcelas" })).toBeVisible();
  await expect(page.getByLabel("Valor da parcela 1", { exact: true })).toHaveValue("500,00");
  await page.getByLabel("Valor da parcela 2", { exact: true }).fill("1450,00");
  await page.getByRole("button", { name: "Registrar venda e criar contas a receber", exact: true }).click();
  await expect(page.getByText("Contas a receber criadas. Recebimento acompanhado pelo Financeiro.", { exact: true })).toBeVisible();
  const jobUrl = page.url();
  await page.goto("/app/financeiro/movimentacoes");
  await page.getByRole("combobox", { name: /^Conta financeira/ }).selectOption({ label: "Conta Gráfica QA" });
  await page.getByRole("textbox", { name: /^Valor/ }).fill("1950,00");
  await page.getByLabel("Cliente", { exact: true }).selectOption({ label: "Horizonte Eventos - Grafica" });
  await page.getByLabel("Referência", { exact: true }).fill(code);
  await page.getByRole("button", { name: "Registrar movimentação", exact: true }).click();
  await page.getByRole("row").filter({ has: page.getByRole("cell", { name: code, exact: true }) }).getByRole("link", { name: "Conciliar", exact: true }).click();
  await page.getByLabel("Buscar por descrição, código do trabalho ou contraparte", { exact: true }).fill(code);
  await page.getByRole("button", { name: "Buscar títulos", exact: true }).click();
  const sinal = page.getByLabel(`Valor para Gráfica ${code} · Sinal`, { exact: true });
  await sinal.fill("501,00");
  await page.getByRole("checkbox", { name: "Conferi os títulos e valores e confirmo a conciliação.", exact: true }).check();
  await page.getByRole("button", { name: "Confirmar conciliação", exact: true }).click();
  await expect(page.getByRole("alert").filter({ hasText: "excede o saldo aberto" })).toBeVisible();
  await expect(sinal).toHaveValue("501,00");
  const reconciliationUrl = page.url();
  await page.goto(jobUrl);
  await page.getByRole("combobox", { name: "Recebimento a identificar", exact: true }).selectOption({ label: (await page.getByRole("combobox", { name: "Recebimento a identificar", exact: true }).locator("option").allTextContents()).find(label => label.includes(code))! });
  await page.getByRole("combobox", { name: "Parcela sugerida", exact: true }).selectOption({ label: "Sinal · R$ 500,00" });
  await page.getByLabel("Valor sugerido", { exact: true }).fill("500,00");
  await page.getByLabel("Justificativa do vínculo", { exact: true }).fill("Cliente informou pagamento do sinal desta OS");
  await page.getByRole("button", { name: "Enviar sugestão ao Financeiro", exact: true }).click();
  await expect(page.getByText("R$ 500,00 · Aguardando Financeiro", { exact: true })).toBeVisible();
  await page.goto(reconciliationUrl);
  await expect(page.getByText("Saldo a conciliar: R$ 1.950,00", { exact: true })).toBeVisible();
  await page.getByLabel("Justificativa da revisão", { exact: true }).fill("Recebimento conferido no extrato");
  await page.getByRole("checkbox", { name: "Conferi o recebimento e confirmo esta decisão.", exact: true }).check();
  await page.getByRole("button", { name: "Registrar revisão", exact: true }).click();
  await expect(page.getByText("Saldo a conciliar: R$ 1.450,00", { exact: true })).toBeVisible();
  await page.getByLabel(`Valor para Gráfica ${code} · Saldo`, { exact: true }).fill("1450,00");
  await page.getByRole("checkbox", { name: "Conferi os títulos e valores e confirmo a conciliação.", exact: true }).check();
  await page.getByRole("button", { name: "Confirmar conciliação", exact: true }).click();
  await expect(page.getByText("Saldo a conciliar: R$ 0,00", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "Confirmar conciliação", exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByText("Saldo a conciliar: R$ 0,00", { exact: true })).toBeVisible();
  await page.goto(jobUrl);
  const financeSummary = page.locator(".fg-card").filter({ has: page.getByText("Resumo financeiro do trabalho", { exact: true }) });
  await expect(financeSummary).toContainText("Recebido e conciliado");
  await expect(financeSummary.locator("dl")).toContainText("R$ 1.950,00");
  await expect(financeSummary).toContainText("R$ 750,00");
  await expect(financeSummary).not.toContainText("Aguardando vínculos confiáveis");
  await page.getByRole("combobox", { name: "Próxima etapa", exact: true }).selectOption("in_production");
  await page.getByRole("button", { name: "Registrar etapa", exact: true }).click();
  await expect(page.getByText("Em produção", { exact: true })).toBeVisible();
  await page.getByRole("combobox", { name: "Próxima etapa", exact: true }).selectOption("waiting");
  await page.getByRole("combobox", { name: "Motivo da espera", exact: true }).selectOption("supplier");
  await page.getByRole("button", { name: "Registrar etapa", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: "Aguardando Fornecedor" })).toBeVisible();
  for (const stage of ["in_production", "ready", "delivered", "closed"]) {
    await page.getByRole("combobox", { name: "Próxima etapa", exact: true }).selectOption(stage);
    await page.getByRole("button", { name: "Registrar etapa", exact: true }).click();
    if (stage !== "closed") await expect(page.getByRole("combobox", { name: "Próxima etapa", exact: true })).toHaveValue("");
  }
  await expect(page.getByText("Trabalho encerrado. O histórico permanece disponível.", { exact: true })).toBeVisible();
  await page.goto("/app/grafica");
  await page.getByLabel("Buscar trabalho", { exact: true }).fill(code);
  await page.getByRole("button", { name: "Filtrar", exact: true }).click();
  const dashboardFinance = page.locator(".fg-card").filter({ has: page.getByText("Visão financeira", { exact: true }) });
  await expect(dashboardFinance).toContainText("R$ 1.950,00");
  await expect(dashboardFinance).toContainText("R$ 750,00");
  await expect(page.getByRole("link", { name: "Encerrado: 1", exact: true })).toBeVisible();
  await expect(page.getByRole("row").filter({ has: page.getByRole("link", { name: code, exact: true }) })).toContainText("Resolver pendência financeira");
  await page.getByRole("combobox", { name: "Etapa", exact: true }).selectOption("in_production");
  await page.getByRole("button", { name: "Filtrar", exact: true }).click();
  await expect(page.getByText("Nenhum trabalho encontrado", { exact: true })).toBeVisible();
  await expect(dashboardFinance).toContainText("R$ 0,00");
});
