import { randomUUID } from "node:crypto";
import { loadEnvFile } from "node:process";
import { Client } from "pg";
import { expect, test, type Page } from "@playwright/test";
import { signInWithRetry } from "./helpers/auth";

test("PJ solicita dias flexíveis, Jaci demo aprova venda e a NF recebe o valor uma vez", async ({ browser }) => {
  test.setTimeout(180_000);
  loadEnvFile(".env");
  const connectionString = process.env.DATABASE_DIRECT_URL!;
  if (!["localhost", "127.0.0.1"].includes(new URL(connectionString).hostname)) throw new Error("Fixture permitida apenas no banco local de demonstração.");
  const admin = new Client({ connectionString }); await admin.connect();
  const marker = `QA-PJ-${Date.now()}`;
  const ownId = randomUUID(), reviewerId = randomUUID(), financeId = randomUUID(), employeeId = randomUUID();
  const ownEmail = `${ownId}@formula.local`, reviewerEmail = `${reviewerId}@formula.local`;
  const template = (await admin.query('select u.id,u.organization_id,e.area_id,e.position_id from "user" u join employees e on e.user_id=u.id where u.email=$1', ["pj.exemplo@formula.local"])).rows[0];
  const org = template.organization_id;
  const prior = (await admin.query("select value from app_settings where organization_id=$1 and key='pj_timeoff_approver'", [org])).rows[0];
  const financeEmail = `${financeId}@formula.local`;
  const credentials = [{ id: ownId, email: ownEmail, name: marker, template: "pj.exemplo@formula.local" }, { id: reviewerId, email: reviewerEmail, name: `Jaci demo ${marker}`, template: "todos.perfis@formula.local" }, { id: financeId, email: financeEmail, name: `Financeiro ${marker}`, template: "financeiro@formula.local" }];
  for (const item of credentials) {
    await admin.query('insert into "user" (id,organization_id,name,email,email_verified,access_status,is_active) values ($1,$2,$3,$4,true,\'active\',true)', [item.id, org, item.name, item.email]);
    await admin.query('insert into account (id,user_id,account_id,provider_id,password) select $1,$2,$2,\'credential\',a.password from account a join "user" u on u.id=a.user_id where u.email=$3 and a.provider_id=\'credential\'', [randomUUID(), item.id, item.template]);
    await admin.query('insert into user_roles (user_id,role_id) select $1,ur.role_id from user_roles ur join "user" u on u.id=ur.user_id where u.email=$2', [item.id, item.template]);
  }
  await admin.query("insert into employees (id,organization_id,user_id,registration_number,full_name,area_id,position_id,employment_type,start_date,current_compensation,recurring_cost_allowance) values ($1,$2,$3,$4,$4,$5,$6,'pj','2020-01-01',3900,300)", [employeeId, org, ownId, marker, template.area_id, template.position_id]);
  const ownSession = await browser.newContext(), reviewSession = await browser.newContext(), financeSession = await browser.newContext();
  const own = await ownSession.newPage(), reviewer = await reviewSession.newPage();
  ownSession.setDefaultTimeout(15_000); reviewSession.setDefaultTimeout(15_000); financeSession.setDefaultTimeout(15_000);
  const login = async (page: Page, email: string) => {
    await signInWithRetry(page, email, process.env.DEMO_USER_PASSWORD!);
  };
  try {
    await login(reviewer, reviewerEmail); await login(own, ownEmail);
    await reviewer.goto("/app/ferias");
    await reviewer.getByLabel("Usuária responsável pelas aprovações PJ (Jaci)").selectOption(reviewerId);
    await reviewer.getByRole("button", { name: "Salvar responsável PJ", exact: true }).click();
    await expect(reviewer.getByRole("status").filter({ hasText: "Alteração salva." })).toBeVisible();
    await own.goto("/portal/ferias");
    await own.getByRole("combobox", { name: "Solicitação", exact: true }).selectOption("sale");
    await expect(own.getByLabel("Quantidade de dias")).toHaveValue("15");
    await own.getByRole("button", { name: "Ver cálculo da sugestão", exact: true }).click();
    await expect(own.getByText(/3.900,00.*30.*15.*1.950,00/)).toBeVisible();
    await own.getByRole("button", { name: "Fechar", exact: true }).click();
    await own.getByLabel("Combinado / observações").fill(`Venda ${marker}`);
    await own.getByRole("button", { name: "Solicitar à Jaci", exact: true }).click();
    await expect(own.getByRole("status").filter({ hasText: "dias reservados" })).toBeVisible();
    await reviewer.reload();
    const section = reviewer.locator("section").filter({ has: reviewer.getByRole("heading", { name: `${marker} · Venda de 15 dias`, exact: true }) });
    await section.locator(".fg-input-wrap").filter({ has: reviewer.locator('[name="amount"]') }).locator('input[type="text"]').fill("1950,00");
    await section.getByRole("button", { name: "Aprovar solicitação", exact: true }).click();
    await expect(section.getByRole("alert")).toHaveCount(0);
    await expect(section).toHaveCount(0);
    await reviewer.goto("/app/nfs");
    await reviewer.locator('button[type="button"]').filter({ hasText: /^Nova composição$/ }).click();
    const form = reviewer.locator("form").filter({ has: reviewer.locator('[name="baseAmount"]') });
    await form.locator('[name="employeeId"]').selectOption(employeeId);
    const competence = new Date().toISOString().slice(0, 7);
    await form.locator('[name="competence"]').fill(competence);
    await form.locator('[name="dueDate"]').fill(`${competence}-28`);
    for (const [name, amount] of [["baseAmount", "3900,00"], ["allowanceAmount", "300,00"]]) {
      await form.locator(".fg-input-wrap").filter({ has: reviewer.locator(`[name="${name}"]`) }).locator('input[type="text"]').fill(amount);
    }
    await form.locator('button[type="submit"]').click();
    await expect(reviewer.getByRole("row").filter({ hasText: marker })).toContainText("6.150,00");
    // Approved reimbursement fixture; inclusion and settlement use the real UI.
    const reimbursementId = randomUUID();
    await admin.query("insert into reimbursement_requests (id,organization_id,employee_id,title,category,amount,expense_date,status) values ($1,$2,$3,$4,'Outros',100,$5,'finance_approved')", [reimbursementId, org, employeeId, `Reembolso ${marker}`, `${competence}-01`]);
    await reviewer.goto("/app/reembolsos");
    await reviewer.getByRole("tab", { name: /^Todos/ }).click();
    await reviewer.getByPlaceholder("Buscar colaborador, descrição ou área...").fill(marker);
    await reviewer.getByRole("row").filter({ hasText: marker }).click();
    await reviewer.locator("button").filter({ hasText: /^Incluir em NF$/ }).click();
    await reviewer.getByRole("radio").check();
    await reviewer.getByRole("button", { name: "Incluir na NF", exact: true }).click();
    await expect.poll(async () => (await admin.query("select included_invoice_request_id from reimbursement_requests where id=$1", [reimbursementId])).rows[0].included_invoice_request_id).toBeTruthy();
    await own.goto("/portal/nfs");
    await expect(own.getByText("Venda de 15 dias de férias PJ autorizada", { exact: true })).toBeVisible();
    await expect(own.locator("body")).toContainText("6.250,00");
    await expect(own.getByText(`Reembolso ${marker}`, { exact: true })).toBeVisible();
    await own.locator('input[type="file"]').setInputFiles({ name: `${marker}.pdf`, mimeType: "application/pdf", buffer: Buffer.from("%PDF-1.4\n1 0 obj<</Type/Catalog>>endobj\n%%EOF") });
    await own.locator(".fg-input-wrap").filter({ has: own.locator('[name="issuedAmount"]') }).locator('input[type="text"]').fill("6250,00");
    await own.getByRole("button", { name: /Enviar NF/ }).click();
    await expect(own.locator("body")).toContainText("Enviada");
    const finance = await financeSession.newPage();
    await login(finance, financeEmail);
    await finance.goto("/app/nfs");
    await finance.getByRole("tab", { name: /^Todas/ }).click();
    await finance.getByPlaceholder("Buscar PJ, matricula ou area...").fill(marker);
    await finance.getByRole("row").filter({ hasText: marker }).click();
    const downloaded = finance.waitForEvent("download");
    await finance.getByRole("button", { name: "Baixar PDF", exact: true }).click();
    const pdf = await downloaded;
    expect(pdf.suggestedFilename()).toBe(`${marker}.pdf`);
    expect(await pdf.failure()).toBeNull();
    const uploaded = (await admin.query("select d.id from documents d join invoice_requests i on i.file_id=d.file_id where i.employee_id=$1", [employeeId])).rows[0];
    const downloadedResponse = await finance.request.get(`/app/documentos/${uploaded.id}/download`);
    expect(downloadedResponse.status()).toBe(200);
    expect((await downloadedResponse.body()).subarray(0, 5).toString()).toBe("%PDF-");
    expect(downloadedResponse.headers()["cache-control"]).toContain("no-store");
    expect((await finance.request.get(`/app/documentos/${randomUUID()}/download`)).status()).toBe(404);
    const count = await admin.query("select count(*)::int n from invoice_request_items i join time_off_requests t on t.id=i.source_time_off_id where t.employee_id=$1", [employeeId]);
    expect(count.rows[0].n).toBe(1);
    await finance.locator(".fg-sheet-root.open").getByRole("button", { name: "Aprovar", exact: true }).click();
    await expect.poll(async () => (await admin.query("select i.status, i.expected_amount, e.amount, e.paid_amount from invoice_requests i join financial_expenses e on e.id=i.financial_expense_id and e.organization_id=i.organization_id where i.employee_id=$1", [employeeId])).rows[0]).toEqual({ status: "approved", expected_amount: "6250.00", amount: "6250.00", paid_amount: "0.00" });
    await expect(finance.getByRole("button", { name: "Marcar pago", exact: true })).toHaveCount(0);
    for (const [index, amount] of ["2000,00", "4250,00"].entries()) {
      await reviewer.goto("/app/financeiro/movimentacoes");
      await reviewer.getByRole("combobox", { name: /^Conta financeira/ }).selectOption({ label: "Conta Gráfica QA" });
      await reviewer.getByRole("combobox", { name: /^Direção/ }).selectOption("out");
      await reviewer.getByRole("textbox", { name: /^Valor/ }).fill(amount);
      await reviewer.getByLabel("Referência", { exact: true }).fill(`${marker}-${index}`);
      await reviewer.getByRole("button", { name: "Registrar movimentação", exact: true }).click();
      await reviewer.getByRole("row").filter({ has: reviewer.getByRole("cell", { name: `${marker}-${index}`, exact: true }) }).getByRole("link", { name: "Conciliar", exact: true }).click();
      await reviewer.getByLabel("Buscar por descrição, código do trabalho ou contraparte", { exact: true }).fill(marker);
      await reviewer.getByRole("button", { name: "Buscar títulos", exact: true }).click();
      await reviewer.getByLabel(new RegExp(`Valor para NF .*${marker}`)).fill(amount);
      await reviewer.getByRole("checkbox", { name: "Conferi os títulos e valores e confirmo a conciliação.", exact: true }).check();
      await reviewer.getByRole("button", { name: "Confirmar conciliação", exact: true }).click();
      await expect(reviewer.getByText("Saldo a conciliar: R$ 0,00", { exact: true })).toBeVisible();
      await own.goto("/portal/nfs");
      const payment = own.getByRole("cell").filter({ hasText: index === 0 ? /^Pagamento parcial/ : /^Pago e conciliado/ });
      await expect(payment).toBeVisible();
      await expect(payment).toContainText(index === 0 ? "Conciliado: R$ 2.000,00 · Saldo: R$ 4.250,00" : "Conciliado: R$ 6.250,00 · Saldo: R$ 0,00");
      await own.goto("/portal/reembolsos");
      const reimbursementCard = own.locator("article").filter({ hasText: `Reembolso ${marker}` });
      await expect(reimbursementCard).toContainText(index === 0 ? "NF parcialmente paga — aguardando quitação" : "Pago pela quitação da NF");
      await reviewer.goto("/app/reembolsos");
      await reviewer.getByRole("tab", { name: /^Todos/ }).click();
      await reviewer.getByPlaceholder("Buscar colaborador, descrição ou área...").fill(marker);
      const reimbursementRow = reviewer.getByRole("row").filter({ hasText: marker });
      await expect(reimbursementRow).toContainText(index === 0 ? "NF parcialmente paga" : "Pago pela quitação da NF");
      await expect(reimbursementRow.getByRole("button", { name: "Marcar pago", exact: true })).toHaveCount(0);
    }
    await own.goto("/portal/ferias");
    await own.getByLabel("Quantidade de dias").fill("10");
    await own.getByLabel("Início do descanso").fill("2090-10-01");
    await expect(own.getByLabel("Fim do descanso (dias corridos)")).toHaveValue("2090-10-10");
    await own.getByLabel("Combinado / observações").fill(`Descanso de dez dias ${marker}`);
    await own.getByRole("button", { name: "Solicitar à Jaci", exact: true }).click();
    await expect(own.getByRole("status").filter({ hasText: "dias reservados" })).toBeVisible();
    await reviewer.goto("/app/ferias");
    const rest = reviewer.locator("section").filter({ has: reviewer.getByRole("heading", { name: `${marker} · Descanso de 10 dias corridos`, exact: true }) });
    await rest.getByRole("button", { name: "Aprovar solicitação", exact: true }).click();
    await expect(rest).toHaveCount(0);
    await own.reload(); await expect(own.locator("body")).toContainText("Descanso aprovado: 10");
    await own.getByRole("combobox", { name: "Solicitação", exact: true }).selectOption("sale");
    await own.getByLabel("Quantidade de dias").fill("1");
    await own.getByLabel("Combinado / observações").fill(`Pedido para recusar ${marker}`);
    await own.getByRole("button", { name: "Solicitar à Jaci", exact: true }).click();
    await expect(own.getByRole("status").filter({ hasText: "dias reservados" })).toBeVisible();
    await reviewer.reload();
    const refused = reviewer.locator("section").filter({ has: reviewer.getByRole("heading", { name: `${marker} · Venda de 1 dias`, exact: true }) });
    await refused.getByRole("button", { name: "Recusar solicitação", exact: true }).click();
    await expect(refused).toHaveCount(0);
    await own.reload();
    await expect(own.locator("body")).toContainText("Venda de 1 dias · Recusada");
    await expect(own.locator("body")).toContainText("Reservados: 0");
  } catch (error) {
    console.error("Financeiro:", await financeSession.pages()[0]?.locator("main").innerText({ timeout: 1000 }).catch(() => "indisponível"));
    console.error("Estado da solicitação de teste:", await reviewer.locator("section").filter({ has: reviewer.getByRole("heading", { name: new RegExp(marker) }) }).allTextContents().catch(() => []));
    throw error;
  } finally {
    if (prior) await admin.query("update app_settings set value=$1 where organization_id=$2 and key='pj_timeoff_approver' and value=$3::jsonb", [JSON.stringify(prior.value), org, JSON.stringify(reviewerId)]);
    else await admin.query("delete from app_settings where organization_id=$1 and key='pj_timeoff_approver' and value=$2::jsonb", [org, JSON.stringify(reviewerId)]);
    await admin.end();
    await Promise.all([ownSession.close(), reviewSession.close(), financeSession.close()]);
  }
});
