import { expect, test } from "@playwright/test";

test("SaaS preserves annual currency prices and updates documented estimates", async ({ page }) => {
  test.setTimeout(90_000);
  page.setDefaultTimeout(15_000);
  const response = await page.request.post("/api/auth/sign-in/email", { data: { email: "todos.perfis@formula.local", password: process.env.DEMO_USER_PASSWORD } });
  expect(response.ok()).toBe(true);
  const marker = `QA-moedas-${Date.now()}`;
  await page.goto("/app/assinaturas");
  await page.locator("button:not([type=submit])").filter({ hasText: /^Cadastrar assinatura$/ }).click();
  const create = page.locator("form").filter({ has: page.locator('[name="cycleAmount"]') });
  await create.locator('[name="name"]').fill(marker);
  await create.locator('[name="category"]').fill("QA");
  await create.getByLabel("Moeda", { exact: true }).selectOption("EUR");
  await create.getByLabel("Periodicidade", { exact: true }).selectOption("annual");
  await create.getByLabel("Valor por ciclo na moeda selecionada").fill("120,00");
  await create.getByText("Cotação estimada para USD ou EUR", { exact: true }).click();
  await create.getByLabel("Cotação estimada em reais").fill("6");
  await create.getByRole("button", { name: "Cadastrar assinatura", exact: true }).click();
  await expect(create.getByRole("alert")).toContainText("data e fonte");
  await expect(create.locator('[name="name"]')).toHaveValue(marker);
  await expect(create.getByLabel("Moeda", { exact: true })).toHaveValue("EUR");
  await expect(create.getByLabel("Valor por ciclo na moeda selecionada")).toHaveValue("120,00");
  await create.getByLabel("Data da cotação").fill("2026-10-02");
  await create.getByLabel("Fonte da cotação").fill("Simulação QA");
  await create.getByRole("button", { name: "Cadastrar assinatura", exact: true }).click();
  const href = await page.getByRole("link").filter({ hasText: marker }).getAttribute("href");
  await page.goto(href!);
  const kpi = (label: string) => page.locator(".fg-kpi").filter({ has: page.getByText(label, { exact: true }) }).locator(".fg-kpi-value");
  await expect(kpi("Custo mensal")).toContainText("60,00");
  await expect(kpi("Custo anualizado")).toContainText("720,00");
  await expect(page.locator("body")).toContainText(/Registre cada cobrança efetiva na aba Cobranças/i);
  await page.getByRole("tab", { name: "Contrato", exact: true }).click();
  await expect(page.locator("body")).toContainText("EUR 120.00 · Anual");
  const edit = page.locator("form").filter({ has: page.locator('[name="cycleAmount"]') });
  await edit.getByText("Cotação estimada para USD ou EUR", { exact: true }).click();
  await edit.getByLabel("Cotação estimada em reais").fill("6,5");
  await edit.getByRole("button", { name: "Salvar estimativa", exact: true }).click();
  await expect(edit.getByRole("status")).toContainText("Estimativa salva");
  await page.reload();
  await expect(page.locator("body")).toContainText("EUR 120.00 · Anual");
  await expect(page.locator("body")).toContainText("R$ 780,00");
  await edit.getByLabel("Moeda", { exact: true }).selectOption("USD");
  await edit.getByLabel("Periodicidade", { exact: true }).selectOption("monthly");
  await edit.getByText("Cotação estimada para USD ou EUR", { exact: true }).click();
  await edit.getByLabel("Cotação estimada em reais").fill("");
  await edit.getByRole("button", { name: "Salvar estimativa", exact: true }).click();
  await expect(edit.getByRole("status")).toContainText("Estimativa salva");
  await page.getByRole("tab", { name: "Resumo", exact: true }).click();
  await expect(kpi("Custo mensal")).toContainText("Estimativa pendente");
  await page.getByRole("tab", { name: "Contrato", exact: true }).click();
  await edit.getByLabel("Moeda", { exact: true }).selectOption("BRL");
  await edit.getByLabel("Periodicidade", { exact: true }).selectOption("annual");
  await edit.getByLabel("Valor por ciclo na moeda selecionada").fill("100,00");
  await edit.getByRole("button", { name: "Salvar estimativa", exact: true }).click();
  await expect(edit.getByRole("status")).toContainText("Estimativa salva");
  await page.getByRole("tab", { name: "Resumo", exact: true }).click();
  await expect(kpi("Custo mensal")).toContainText("8,33");
  await expect(kpi("Custo anualizado")).toContainText("100,00");
});
