import { expect, test } from "@playwright/test";
import { signInWithRetry } from "./helpers/auth";

test("registra cobrança SaaS efetiva com câmbio/IOF e cria AP uma única vez", async ({ page }) => {
  test.setTimeout(90_000);
  page.setDefaultTimeout(15_000);
  await signInWithRetry(page, "todos.perfis@formula.local", process.env.DEMO_USER_PASSWORD!);
  const marker = `QA-cobranca-${Date.now()}`;
  await page.goto("/app/assinaturas");
  await page.locator("button:not([type=submit])").filter({ hasText: /^Cadastrar assinatura$/ }).click();
  const create = page.locator("form").filter({ has: page.locator('[name="cycleAmount"]') });
  await create.locator('[name="name"]').fill(marker);
  await create.locator('[name="category"]').fill("Validação financeira");
  await create.getByLabel("Moeda", { exact: true }).selectOption("EUR");
  await create.getByLabel("Periodicidade", { exact: true }).selectOption("monthly");
  await create.getByLabel("Valor por ciclo na moeda selecionada").fill("50,00");
  await create.getByText("Cotação estimada para USD ou EUR", { exact: true }).click();
  await create.getByLabel("Cotação estimada em reais").fill("6");
  await create.getByLabel("Data da cotação").fill("2026-10-01");
  await create.getByLabel("Fonte da cotação").fill("Fatura QA");
  await create.getByRole("button", { name: "Cadastrar assinatura", exact: true }).click();
  await page.getByPlaceholder("Nome, fornecedor, categoria...").fill(marker);
  const href = await page.getByRole("link").filter({ hasText: marker }).getAttribute("href");
  expect(href).toBeTruthy();
  await page.goto(`${href}?tab=cobrancas`);
  const chargeForm = page.locator("form").filter({ has: page.getByRole("button", { name: "Registrar cobrança", exact: true }) });
  await chargeForm.locator('[name="competence"]').fill("2026-12");
  await chargeForm.locator('[name="chargedAt"]').fill("2026-12-02");
  await chargeForm.locator('[name="dueDate"]').fill("2026-12-10");
  await chargeForm.locator('[name="originalAmount"]').fill("50,00");
  await chargeForm.locator('[name="effectiveExchangeRate"]').fill("6,20");
  await chargeForm.locator('[name="iofAmountBrl"]').fill("5,00");
  await chargeForm.locator('[name="feeAmountBrl"]').fill("2,00");
  await chargeForm.locator('[name="totalAmountBrl"]').fill("317,00");
  await chargeForm.getByRole("button", { name: "Registrar cobrança", exact: true }).click();
  await expect(chargeForm.getByRole("status")).toContainText("conta a pagar criada");
  await expect(page.locator("td").filter({ hasText: "R$ 317,00" })).toBeVisible();
  await expect(page.getByText("Em aberto", { exact: true })).toBeVisible();

  // Reenviar a mesma competência é idempotente e não cria uma segunda AP.
  await chargeForm.locator('[name="totalAmountBrl"]').fill("400,00");
  await chargeForm.getByRole("button", { name: "Registrar cobrança", exact: true }).click();
  await page.reload();
  await expect(page.locator("td").filter({ hasText: "R$ 317,00" })).toHaveCount(1);
  await expect(page.locator("td").filter({ hasText: "R$ 400,00" })).toHaveCount(0);
  await page.getByText("Corrigir cobrança de 2026-12", { exact: true }).click();
  const correction = page.locator("form").filter({ has: page.getByRole("button", { name: "Salvar correção da cobrança", exact: true }) });
  await correction.locator('[name="effectiveExchangeRate"]').fill("6,50");
  await correction.locator('[name="totalAmountBrl"]').fill("332,00");
  await correction.getByLabel("Motivo da correção", { exact: true }).fill("Cotação efetiva conferida no extrato");
  await correction.getByRole("button", { name: "Salvar correção da cobrança", exact: true }).click();
  await expect(correction.getByRole("status")).toContainText("mesma conta a pagar");
  await page.reload();
  const chargeRow = page.getByRole("row").filter({ has: page.getByRole("cell", { name: /^2026-12/ }) });
  await expect(chargeRow).toHaveCount(1);
  await expect(chargeRow.getByRole("cell").nth(3)).toContainText("R$ 332,00");
  await expect(chargeRow.getByRole("cell").nth(3)).not.toContainText("R$ 317,00");
  await page.getByText("Histórico de correções de 2026-12", { exact: true }).click();
  await expect(chargeRow).toContainText("De R$ 317,00 para R$ 332,00");
  await expect(chargeRow).toContainText("Motivo: Cotação efetiva conferida no extrato");
  await page.getByRole("link", { name: "Em aberto", exact: true }).click();
  const payable = page.getByRole("row").filter({ hasText: marker });
  await expect(payable).toHaveCount(1);
  await expect(payable).toContainText("R$ 332,00");

  await page.goto(`${href}?tab=cobrancas`);
  await page.getByText("Cancelar cobrança de 2026-12", { exact: true }).click();
  const cancellation = page.locator("form").filter({ has: page.getByRole("button", { name: "Confirmar cancelamento da cobrança", exact: true }) });
  await cancellation.getByLabel("Motivo do cancelamento", { exact: true }).fill("Fatura duplicada cancelada pelo fornecedor");
  await cancellation.getByRole("checkbox").check();
  await cancellation.getByRole("button", { name: "Confirmar cancelamento da cobrança", exact: true }).click();
  // Revalidation may replace the submitted form immediately; persisted state is the acceptance.
  await expect(page.getByRole("link", { name: "Cancelado", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText(/Motivo: Fatura duplicada cancelada pelo fornecedor/)).toBeVisible();
  await expect(page.getByText("Corrigir cobrança de 2026-12", { exact: true })).toHaveCount(0);
  await page.getByRole("link", { name: "Cancelado", exact: true }).click();
  await expect(payable).toHaveCount(1);
  await expect(payable).toContainText("Cancelado");
  await expect(payable).toContainText("R$ 332,00");

  // Replacement is a new obligation; the cancelled AP/history remain visible.
  await page.goto(`${href}?tab=cobrancas`);
  await chargeForm.locator('[name="competence"]').fill("2026-12");
  await chargeForm.locator('[name="chargedAt"]').fill("2026-12-03");
  await chargeForm.locator('[name="dueDate"]').fill("2026-12-15");
  await chargeForm.locator('[name="originalAmount"]').fill("50,00");
  await chargeForm.locator('[name="effectiveExchangeRate"]').fill("6,50");
  await chargeForm.locator('[name="iofAmountBrl"]').fill("0");
  await chargeForm.locator('[name="feeAmountBrl"]').fill("0");
  await chargeForm.locator('[name="totalAmountBrl"]').fill("325,00");
  await chargeForm.getByRole("button", { name: "Registrar cobrança", exact: true }).click();
  await expect(chargeForm.getByRole("status")).toContainText("conta a pagar criada");
  await page.reload();
  await expect(chargeRow).toHaveCount(2);
  await expect(page.getByRole("link", { name: "Cancelado", exact: true })).toHaveCount(1);
  await expect(page.getByRole("link", { name: "Em aberto", exact: true })).toHaveCount(1);
  await page.getByRole("link", { name: "Em aberto", exact: true }).click();
  await expect(payable).toHaveCount(2);
  await expect(payable.filter({ hasText: "R$ 325,00" })).toHaveCount(1);
  await expect(payable.filter({ hasText: "R$ 332,00" })).toContainText("Cancelado");
});
