export const roleKeys = [
  "technical_admin",
  "director",
  "finance",
  "hr_admin",
  "it_governance",
  "leadership",
  "employee",
] as const;

export type RoleKey = (typeof roleKeys)[number];

export const roleLabels: Record<RoleKey, string> = {
  technical_admin: "Admin Tecnico",
  director: "Diretoria",
  finance: "Financeiro",
  hr_admin: "RH/Admin",
  it_governance: "TI/Governanca",
  leadership: "Lideranca",
  employee: "Colaborador",
};

export const permissionKeys = [
  "dashboard.configure",
  "dashboard.read",
  "finance.read",
  "finance.write",
  "finance.export",
  "finance.configure",
  "clients.configure",
  "clients.read",
  "clients.write",
  "clients.read_limited",
  "people.configure",
  "people.read",
  "people.write",
  "people.read_team",
  "people.read_own",
  "compensation.read",
  "compensation.write",
  "compensation.read_own",
  "documents.read_sensitive",
  "documents.write",
  "documents.read_own",
  "timeoff.read",
  "timeoff.write",
  "timeoff.read_team",
  "timeoff.read_own",
  "invoices.read",
  "invoices.write",
  "invoices.approve",
  "invoices.read_own",
  "reimbursements.read",
  "reimbursements.write",
  "reimbursements.approve_team",
  "reimbursements.approve_finance",
  "reimbursements.read_own",
  "equipment.configure",
  "equipment.read",
  "equipment.write",
  "equipment.read_team",
  "equipment.read_own",
  "access_records.configure",
  "access_records.read",
  "access_records.write",
  "access_records.read_team",
  "access_records.read_own",
  "saas.configure",
  "saas.read",
  "saas.write",
  "saas.read_linked",
  "lifecycle.read",
  "lifecycle.write",
  "alerts.read",
  "alerts.write",
  "audit.read",
  "audit.read_limited",
  "settings.manage",
  "settings.read",
] as const;

export type PermissionKey = (typeof permissionKeys)[number];

export const permissionDescriptions: Record<PermissionKey, string> = {
  "dashboard.configure": "Configurar dashboard executivo",
  "dashboard.read": "Visualizar dashboard executivo",
  "finance.read": "Visualizar dados financeiros",
  "finance.write": "Criar e alterar dados financeiros",
  "finance.export": "Exportar dados financeiros",
  "finance.configure": "Configurar cadastros financeiros",
  "clients.configure": "Configurar clientes",
  "clients.read": "Visualizar clientes",
  "clients.write": "Criar e alterar clientes",
  "clients.read_limited": "Visualizar clientes com escopo limitado",
  "people.configure": "Configurar colaboradores",
  "people.read": "Visualizar colaboradores",
  "people.write": "Criar e alterar colaboradores",
  "people.read_team": "Visualizar equipe direta",
  "people.read_own": "Visualizar proprio cadastro",
  "compensation.read": "Visualizar remuneracao",
  "compensation.write": "Criar e alterar remuneracao",
  "compensation.read_own": "Visualizar propria remuneracao",
  "documents.read_sensitive": "Visualizar documentos sensiveis",
  "documents.write": "Criar e alterar documentos",
  "documents.read_own": "Visualizar proprios documentos",
  "timeoff.read": "Visualizar ferias e ausencias",
  "timeoff.write": "Criar e alterar ferias e ausencias",
  "timeoff.read_team": "Visualizar ferias e ausencias da equipe",
  "timeoff.read_own": "Visualizar proprias ferias e ausencias",
  "invoices.read": "Visualizar notas fiscais",
  "invoices.write": "Criar e alterar notas fiscais",
  "invoices.approve": "Aprovar notas fiscais",
  "invoices.read_own": "Visualizar proprias notas fiscais",
  "reimbursements.read": "Visualizar reembolsos",
  "reimbursements.write": "Criar e alterar reembolsos",
  "reimbursements.approve_team": "Aprovar reembolsos da equipe",
  "reimbursements.approve_finance": "Aprovar reembolsos pelo financeiro",
  "reimbursements.read_own": "Visualizar proprios reembolsos",
  "equipment.configure": "Configurar patrimonio",
  "equipment.read": "Visualizar equipamentos",
  "equipment.write": "Criar e alterar equipamentos",
  "equipment.read_team": "Visualizar equipamentos da equipe",
  "equipment.read_own": "Visualizar proprios equipamentos",
  "access_records.configure": "Configurar acessos",
  "access_records.read": "Visualizar acessos",
  "access_records.write": "Criar e alterar acessos",
  "access_records.read_team": "Visualizar acessos da equipe",
  "access_records.read_own": "Visualizar proprios acessos",
  "saas.configure": "Configurar assinaturas e licencas",
  "saas.read": "Visualizar assinaturas e licencas",
  "saas.write": "Criar e alterar assinaturas e licencas",
  "saas.read_linked": "Visualizar licencas vinculadas",
  "lifecycle.read": "Visualizar checklists de admissao e desligamento",
  "lifecycle.write": "Criar e alterar checklists de admissao e desligamento",
  "alerts.read": "Visualizar central de alertas",
  "alerts.write": "Gerar, resolver e dispensar alertas",
  "audit.read": "Visualizar logs de auditoria",
  "audit.read_limited": "Visualizar logs de auditoria limitados",
  "settings.manage": "Gerenciar configuracoes",
  "settings.read": "Visualizar configuracoes",
};
